import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../components/navbar'

import ReactMarkdown from 'react-markdown'

import { remark } from 'remark';
import html from 'remark-html';
import path from 'path';
import fs from 'fs';
import matter from 'gray-matter';
import md from 'markdown-it';

import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import 'katex/dist/katex.min.css' // `rehype-katex` does not import the CSS for you
import remarkGfm from 'remark-gfm'

import { useMDXComponent } from 'next-contentlayer/hooks';
// import { allPages } from 'contentlayer/generated';

import {MDXProvider} from '@mdx-js/react'
import Post from '../posts/home1.mdx'

// export async function getPostData(id) {
//   const fullPath = path.join("public", `index.md`);
//   const fileContents = fs.readFileSync(fullPath, 'utf8');

//   // Use gray-matter to parse the post metadata section
//   // const matterResult = matter(fileContents);

//   // Use remark to convert markdown into HTML string
//   const processedContent = await remark()
//     .use(html)
//     .process(matterResult.content);
//   const contentHtml = processedContent.toString();

//   // Combine the data with the id and contentHtml
//   return {
//     id,
//     contentHtml,
//     // ...matterResult.data,
//   };
// }


export async function getStaticProps() {
  // Add the "await" keyword like this:
  const postData = 2
  const fileName = fs.readFileSync(`public/index.md`, 'utf-8');
  const { data: frontmatter, content } = matter(fileName);
  return {

    props: {

      frontmatter,
      content
    },

  };
}

export default function Home({frontmatter, content} : any) {
  const markdown = `
# Hello *world*! \n $a^2$ https://reactjs.com. \n\n $$a^2+b^2=c^2$$
A paragraph with *emphasis* and **strong importance**.

> A block quote with ~strikethrough~ and a URL: https://reactjs.org.

* Lists
* [ ] todo
* [x] done

A table:

| a | b |
| - | - |

| 1    | 2   | 3    | 4       | 5    |
|------|-----|------|---------|------|
| 2    | 12  | 4214 | 12421   | 4124 |
| 12   | 124 | 124  | 21421   | 14   |
| 4142 | 124 | 124  | 2141241 | 124  |

gudes

~~~js
console.log('It works!')
~~~

`
const components = {
  em: (props : any) => <i {...props} />
}
  return (
    <div className={styles.container}>
      <div>
        <Navbar />
      </div>
      <div className='prose mx-auto'>
        <MDXProvider components={components}>
          <Post />
        </MDXProvider>
      <div>
      <ReactMarkdown
        remarkPlugins={[[remarkGfm, {singleTilde: false}],[remarkMath]]}
        rehypePlugins={[rehypeKatex]}
      >
        {markdown}
      </ReactMarkdown>
      </div>
      <h1>{frontmatter.title}</h1>
      <div dangerouslySetInnerHTML={{ __html: md().render(content) }} />
      </div>
      <h1 className="text-3xl font-bold underline hover:text-2xl">
        Hello world!
      </h1>
      <div>
        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
          Button
        </button>
        <button className=" hover:bg-blue-700 text-black font-bold py-2 px-4 rounded">
          Button 2
        </button>
      </div>
      <Head>
        <title>Lambert Theisen - Researcher, Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
